
server:
  port: 8081

spring:
  application:
    name: person-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

logging:
  level:
    com.hazelcast: DEBUG
    org.hibernate: DEBUG
